name: Build

env:
  CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-*"

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-13
            macosx_deployment_target: "13.0"
          - os: macos-14
            macosx_deployment_target: "14.0"
    if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.21.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macosx_deployment_target }}
          CIBW_BEFORE_BUILD_MACOS: "brew install libomp"
          CIBW_ENVIRONMENT_MACOS: >
            CC=/usr/bin/clang
            CXX=/usr/bin/clang++
            CPPFLAGS="-Xclang -fopenmp"
            CFLAGS="-I$(brew --prefix libomp)/include"
            CXXFLAGS="-I$(brew --prefix libomp)/include"
            LDFLAGS="-Wl,-rpath,$(brew --prefix libomp)/lib -L$(brew --prefix libomp)/lib -lomp"
            MACOSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl


  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz


  upload_pypi:
    name: Upload to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi_release
    permissions:
      id-token: write
    if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
